name: Masser
version: '0.1'
main: yaroster.masser.Masser
api-version: '1.20'
commands:
  invisiblehelp:
  invisibleplugins:
  invisibleversion:
  invisibleseed:
  l:
  m:
  pm:
  r:
  spawn:
  appear:
  top:
  bed:
  a:
  location:
  extermine:
  sethealth:
  setfood:
  setlevel:
  givexp:
  to:
  group:
  g:
  setspawn:
  back:
  unbreak:
  plot:
  c:
  clan:
  tc:
  shop:
  restart:
  maj:
  spawner:
  teleporter:
  world:
  invisibleban:
  invisiblebanip:
  invisiblekick:
  invisible:
  distance:
  ip:
  reset:
  chat:
  lag:
  prison:
  jail:
  unjail:
  msg:
  suicide:
  sanguine:
  afk:
  mute:
  unmute:
  open:
  invisiblereload: